name: test_4

on:
  schedule:
    - cron: '*/5 * * * *'
    
  workflow_dispatch:
jobs:
  test_4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
           ref: main
      - uses: peter-evans/create-pull-request@v4
        with:
          base: main        
          branch: prod
